name: tjdb
version: 2

handle:
- rewrite: if(!-f && !-d && %{REQUEST_URI} ~ "me/?$") goto "me.php"
- rewrite: if(!-f && !-d && path ~ "^/search/([^/]*)$") goto "search.php?q=$1&page=1"
- rewrite: if(!-f && !-d && path ~ "^/search/([^/]*)/(\d+)?$") goto "search.php?q=$1&page=$2"
- rewrite: if(!-f && !-d && %{REQUEST_URI} ~ "login/?$") goto "login.php"
- rewrite: if(!-f && !-d && %{REQUEST_URI} ~ "contact/?$") goto "contact.php"
- rewrite: if(!-f && !-d && path ~ "^/course/([0-9]*)/?") goto "viewcourse.php?q=$1"
- rewrite: if(!-f && !-d && %{REQUEST_URI} ~ "changelog$") goto "changelog/index.html"
